<?php

namespace App\Http\Requests\PaymentHistory;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\ValidationException;

class PaymentHistoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'first_name'=>'required|string',
            'last_name'=>'required|string',
            'email'=>'required|email:rfc,dns',
            'zakat'=>'required|regex:/^[0-9]+(\.[0-9]{1,10})?$/',
            'sadaqah'=>'required|regex:/^[0-9]+(\.[0-9]{1,10})?$/',
            'riba'=>'required|regex:/^[0-9]+(\.[0-9]{1,10})?$/'
        ];
    }
    public function messages()
    {
        return [
            'first_name.required'=>'First name is required',
            'first_name.string'=>'First format is not correct',
            'last_name.required'=>'Last name is required',
            'last_name.string'=>'Last format is not correct',
            'email.required'=>'Email name is required',
            'email.email'=>'Email format is not correct',
            'zakat.required'=>'Zakat field is required',
            'zakat.regex'=>'Zakat format is not correct',
            'sadaqah.required'=>'Sadaqah field is required',
            'sadaqah.regex'=>'Sadaqah format is not correct',
            'riba.required'=>'Riba field is required',
            'riba.regex'=>'Riba format is not correct'
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        $errors = (new ValidationException($validator))->errors();
        throw new HttpResponseException(response()->json(['status' => 0, 'errors'=> $errors]));

        //parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
